
services:
  neo4j:
    image: neo4j:5.24.2
    container_name: dharana-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
volumes:
  neo4j_data: {}
  neo4j_logs: {}
